name: rus_tili_ai_ustoz
description: "Rus tilini o'rgatuvchi AI mobil ilovasi."
publish_to: 'none'
version: 1.0.1+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # AI & Logic
  google_generative_ai: ^0.4.0
  flutter_dotenv: ^5.1.0
  provider: ^6.1.1
  permission_handler: ^11.3.0
  
  # Speech
  speech_to_text: ^6.6.0
  flutter_tts: ^3.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
